// Auto-generated from partition/AIR6208.csv
// DO NOT EDIT MANUALLY
// Generated by buildx.lua

#ifndef LUAT_PARTITION_MEM_AIR6208_H
#define LUAT_PARTITION_MEM_AIR6208_H

// AIR6208 (8192KB Flash)
#define LUAT_FS_SIZE                3392      // 文件系统大小 (KB)
#define LUAT_SCRIPT_SIZE            512      // 脚本大小 (KB)

#endif /* LUAT_PARTITION_MEM_AIR6208_H */
